### ISSUE TITLE
List on Graylog Marketplace

### ISSUE THREAD

**Issue by lennartkoopmann** [zooniverse/gelfcat#1]
We have launched the beta of the Graylog Marketplace: https://marketplace.graylog.org/

The Marketplace is the central directory of all Graylog add-ons and integrations, including GELF libraries.

You would help us a lot if you could submit your tool there. :)

**Comment by adammcmaster** [comment]
Cool, thanks for letting me know. I've submitted this now.

**Comment by lennartkoopmann** [comment]
Thank you! :+1: :shipit:
